### ISSUE TITLE
g-recaptcha-response field is required

### ISSUE THREAD

**Issue by k1n3t1c** [sijad/flarum-ext-recaptcha#2]
![image](https://cloud.githubusercontent.com/assets/20934051/20365175/f4c65b3c-ac13-11e6-94b9-8cd7e92657f2.png)

When I click on `Sign Up` after solving captcha I am receiving that error.

**Comment by fkndean** [comment]
#3

**Comment by sijad** [comment]
what browser are you suing? I just tested this extension and couldn't reproduce this.

**Comment by k1n3t1c** [comment]
I'm on chrome. sorry about the PR that was accident.
I even tried a fresh installation and kept reproducing this when i did `composer require sijad/flarum-ext-recaptcha` installs fine with the `google/recaptcha` 1.1.2.

I'm on flarum`beta6`

**Comment by sijad** [comment]
is there any error in your browser console?

**Comment by k1n3t1c** [comment]
![image](https://cloud.githubusercontent.com/assets/20934051/20377306/4bdb7f9a-ac5c-11e6-9eba-b01fe76c4dd7.png)

**Comment by sijad** [comment]
can I also know what other extension did you install?

**Comment by sijad** [comment]
I just tried this extension with chrome on fresh install and I couldn't reprodcue this

**Comment by k1n3t1c** [comment]
Then it must be one of my extensions.. :(

```
        "flarum/core": "^v0.1.0",
        "flarum/flarum-ext-akismet": "^0.1.0",
        "flarum/flarum-ext-approval": "^0.1.0",
        "flarum/flarum-ext-auth-facebook": "^0.1.0",
        "flarum/flarum-ext-auth-github": "^0.1.0",
        "flarum/flarum-ext-auth-twitter": "^0.1.0",
        "flarum/flarum-ext-bbcode": "^0.1.0",
        "flarum/flarum-ext-emoji": "^0.1.0",
        "flarum/flarum-ext-english": "^0.1.0",
        "flarum/flarum-ext-flags": "^0.1.0",
        "flarum/flarum-ext-likes": "^0.1.0",
        "flarum/flarum-ext-lock": "^0.1.0",
        "flarum/flarum-ext-markdown": "^0.1.0",
        "flarum/flarum-ext-mentions": "^0.1.0",
        "flarum/flarum-ext-pusher": "^0.1.0",
        "flarum/flarum-ext-sticky": "^0.1.0",
        "flarum/flarum-ext-subscriptions": "^0.1.0",
        "flarum/flarum-ext-suspend": "^0.1.0",
        "flarum/flarum-ext-tags": "^0.1.0",
        "yongteak/flarum-ext-korean": "^0.1.0@beta",
        "flarumes/flarum-ext-spanish": "^0.1.0@beta",
        "sijad/flarum-ext-auth-steam": "^0.1.7",
        "xengine/flarum-ext-signature": "^0.1.1",
        "davis/flarum-ext-socialprofile": "^0.2.2",
        "sijad/flarum-ext-pages": "^0.1.0@beta",
        "jordanjay29/flarum-ext-summaries": "^0.2.0",
        "davis/flarum-ext-securehttps": "^0.1.0@beta",
        "s9e/flarum-ext-autoimage": "^1.0",
        "s9e/flarum-ext-autovideo": "^1.0",
        "sijad/flarum-ext-details": "^0.1.2",
        "wiwatsrt/flarum-ext-best-answer": "^0.1.0@beta",
        "jsthon/flarum-ext-simplified-chinese": "^0.1.0@beta",
        "flagrow/flarum-ext-analytics": "^0.5.0",
        "davis/flarum-ext-customfooter": "^0.1.0@beta",
        "sijad/flarum-ext-links": "^0.1.0@beta",
        "flagrow/flarum-ext-latex": "^0.1.1",
        "avatar4eg/flarum-ext-geotags": "^0.1.2",
        "avatar4eg/flarum-ext-users-list": "^0.1.1",
        "vingle/flarum-share-social": "^0.1.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "aws/aws-sdk-php": "^3.19",
        "flagrow/upload": "^0.3.1",
        "zendframework/zend-stratigility": "1.2.1",
        "pnobbe/flarum-ext-oauth-discord": "^v1.0.1beta6",
        "terabin/flarum-ext-sitemap": "^1.0@beta",
        "google/recaptcha": "1.1.2",
        "sijad/flarum-ext-recaptcha": "^0.0.1"
```

**Comment by sijad** [comment]
could you please test this with disabled extension? or on a fresh installation without any extension?

**Comment by fkndean** [comment]
Ok I found out the culprit extension, it is the Google Analytics one... lol

**Comment by k1n3t1c** [comment]
Ok, after further testing I found that it does not work with the extensions for auths such as `flarum/flarum-ext-auth-facebook`, `flarum/flarum-ext-auth-github`, `pnobbe/flarum-ext-oauth-discord`. They work fine without the recaptcha plugin, perhaps you need to support it for those extensions? Sorry been up for 2 days x.x my mind is elsewhere.

Another thing to mention is that the recaptcha works fine on normal registration, but not the other auths.

**Comment by sijad** [comment]
this should be fixed with https://github.com/sijad/flarum-ext-recaptcha/commit/df7bc6c96132434c8a9426e5eafe35d0302cd125
could you please upgrade to `dev-master` and try latest changes?

**Comment by k1n3t1c** [comment]
@sijad Thanks for updating, but it didn't seem to fix the issue with the other auth methods. However, I did notice stuff like Twitter auth working, but Facebook, Github, Discord doesn't work.

**Comment by sijad** [comment]
are you sure you did upgrade to `dev-master`? I've tested it with github

**Comment by k1n3t1c** [comment]
Yes I am on `dev-master`.

Thanks again 👍 

![image](https://cloud.githubusercontent.com/assets/20934051/20400151/9eae6a74-acc1-11e6-91a7-dcca4889db2d.png)

**Comment by sijad** [comment]
can you please also remove all `.js` files in your asset folder and try again?

**Comment by k1n3t1c** [comment]
@sijad that did the trick. So I'm guessing that's like a cache it keeps?

Thanks for updating and being patient! 👍 ⚡️
